function AIDietTips() {
  const tips = [
    { icon: "🌙", text: "Sleep at least 7–8 hours tonight" },
    { icon: "🧘‍♂️", text: "Take a short meditation break" },
    { icon: "💧", text: "Drink 8 glasses of water" },
    { icon: "🍏", text: "Add leafy greens to lunch" }
  ];

  const mondayPlan = {
    day: "Monday",
    breakfast: "Oats + Banana + Almonds",
    lunch: "Grilled Chicken + Rice",
    dinner: "Chapati + Dal + Veg Sabzi",
    snacks: "Apple / Nuts",
    calories: "1800 kcal"
  };

  return (
    <div className="diet-tips-container">

      {/* LEFT CARD */}
      <div className="card tips-card">
        <h2>Daily AI Tips</h2>
        <p className="subtitle">
          Personalized health recommendations for today
        </p>

        <ul className="tips-list">
          {tips.map((item, i) => (
            <li key={i}>
              <span className="icon">{item.icon}</span>
              {item.text}
            </li>
          ))}
        </ul>
      </div>

      {/* RIGHT CARD */}
      <div className="card diet-card">
        <h2>AI Diet Plan</h2>
        <p className="subtitle">
          Your personalized weekly meal plan generated by AI
        </p>

        <h3 className="day">{mondayPlan.day}</h3>

        <p><strong>Breakfast:</strong> {mondayPlan.breakfast}</p>
        <p><strong>Lunch:</strong> {mondayPlan.lunch}</p>
        <p><strong>Dinner:</strong> {mondayPlan.dinner}</p>
        <p><strong>Snacks:</strong> {mondayPlan.snacks}</p>

        <p className="calories">
          🔥 {mondayPlan.calories}
        </p>
      </div>

    </div>
  );
}

export default AIDietTips;
